server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Favicon específico - sin log, cache largo
    location = /favicon.ico {
        access_log off;
        log_not_found off;
        expires 7d;
        add_header Cache-Control "public";
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg)$ {
        expires 0;
        add_header Cache-Control "no-cache";
    }
}
