version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: autogestion_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: autogestion_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: autogestion_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/autogestion_bd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: adminpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: autogestion_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres_data: